version: 1
directus: 9.23.1
vendor: postgres
collections:
  - collection: articles
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: status
      archive_value: archived
      collapse: open
      collection: articles
      color: null
      display_template: null
      group: null
      hidden: false
      icon: article
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: draft
    schema:
      name: articles
fields:
  - collection: articles
    field: author
    type: uuid
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: author
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options:
        enableCreate: false
      readonly: false
      required: false
      sort: null
      special:
        - m2o
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: author
      table: articles
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: directus_users
      foreign_key_column: id
  - collection: articles
    field: content
    type: text
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: content
      group: null
      hidden: false
      interface: input-rich-text-html
      note: null
      options:
        toolbar:
          - aligncenter
          - alignjustify
          - alignleft
          - alignnone
          - alignright
          - backcolor
          - blockquote
          - bold
          - bullist
          - code
          - copy
          - customImage
          - customLink
          - customMedia
          - cut
          - fontselect
          - fontsizeselect
          - forecolor
          - fullscreen
          - h1
          - h2
          - h3
          - h4
          - h5
          - h6
          - hr
          - indent
          - italic
          - ltr rtl
          - numlist
          - outdent
          - paste
          - redo
          - remove
          - removeformat
          - selectall
          - strikethrough
          - subscript
          - superscript
          - table
          - underline
          - undo
          - unlink
          - visualaid
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: content
      table: articles
      data_type: text
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: articles
    field: date_created
    type: timestamp
    meta:
      collection: articles
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: date_created
      table: articles
      data_type: timestamp with time zone
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: articles
    field: date_updated
    type: timestamp
    meta:
      collection: articles
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_updated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - date-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: date_updated
      table: articles
      data_type: timestamp with time zone
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: articles
    field: id
    type: integer
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: id
      table: articles
      data_type: integer
      default_value: nextval('articles_id_seq'::regclass)
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_nullable: false
      is_unique: true
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: true
      foreign_key_table: null
      foreign_key_column: null
  - collection: articles
    field: slug
    type: string
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: slug
      group: null
      hidden: false
      interface: input
      note: null
      options:
        slug: true
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: slug
      table: articles
      data_type: character varying
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: true
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: articles
    field: status
    type: string
    meta:
      collection: articles
      conditions: null
      display: labels
      display_options:
        choices:
          - text: $t:published
            value: published
            foreground: '#FFFFFF'
            background: var(--primary)
          - text: $t:draft
            value: draft
            foreground: '#18222F'
            background: '#D3DAE4'
          - text: $t:archived
            value: archived
            foreground: '#FFFFFF'
            background: var(--warning)
        showAsDot: true
      field: status
      group: null
      hidden: false
      interface: select-dropdown
      note: null
      options:
        choices:
          - text: $t:published
            value: published
          - text: $t:draft
            value: draft
          - text: $t:archived
            value: archived
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: status
      table: articles
      data_type: character varying
      default_value: draft
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: articles
    field: title
    type: string
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: title
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: title
      table: articles
      data_type: character varying
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
relations:
  - collection: articles
    field: author
    related_collection: directus_users
    meta:
      junction_field: null
      many_collection: articles
      many_field: author
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    schema:
      table: articles
      column: author
      foreign_key_table: directus_users
      foreign_key_column: id
      constraint_name: articles_author_foreign
      on_update: NO ACTION
      on_delete: NO ACTION
